Eshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings
 


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("store.urls" , namespace='store'))

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from .views.cart import cart_detail, add_to_cart, remove_from_cart
from .views.home import Index
from .views.home import product_details
from .views.signup import Signup
from .views.login import Login, logout
from .views.checkout import Checkout
from .views.orders import OrderView

from .middlewares.auth import auth_middleware

app_name = 'store'

urlpatterns = [
    path("", Index.as_view(), name ="home"),
    path("signup/", Signup.as_view(), name="signup"),
    path("login/", Login.as_view(), name="login"), 
    path("logout/", logout, name="logout"),
    path('products/<int:pk>/', product_details, name='product_details'),
    path('cart/', cart_detail, name='cart'),
    path('carts/add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('carts/remove_from_cart/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    # path('carts/clear_all_cart/', clear_all_cart, name='clear_all_cart'),
    path("check_out/", Checkout.as_view(), name="checkout"),
    
    path("orders/", auth_middleware(OrderView.as_view()), name="orders"),
]

store/models/cart.py
from django.db import models

from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver

from store.models.product import Product

User = get_user_model()
# Create your models here.


class Cart(models.Model):
    user = models.OneToOneField(User, related_name='cart', on_delete=models.CASCADE)
    items = models.ManyToManyField(Product)
    updated_at = models.DateTimeField(auto_now=True)


    def total_price(self):
        total = 0
        for item in self.items.all():
            total += item.price

        return total

    def __str__(self):
        return str(self.user)



@receiver(post_save, sender=User)
def create_user_cart(sender, instance, created, **kwargs):
    if created:
        Cart.objects.create(user=instance)

store/models/category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20)


    @staticmethod
    def get_all_categories():
        return Category.objects.all()
    
   

    def __str__(self):
        return self.name
    


store/models/customer.py
from django.db import models

class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    email = models.EmailField()
    password = models.CharField(max_length=200)
    
    def register(self):
        self.save()
  
    def __str__(self):
        return self.email
    
    @staticmethod
    def get_customer_by_email(email):
        try:
            return Customer.objects.get(email= email)
        except:
            return False
    def isExists(self):
        if Customer.objects.filter(email=self.email):
            return True
        return False

    
    
    

store/models/orders.py
from django.db import models
from .product import Product
from .customer import Customer
import datetime

class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.IntegerField()
    address = models.CharField(max_length=300, default="", blank=True)
    phone = models.CharField(max_length=60, default="", blank=True)
    date = models.DateTimeField(default=datetime.datetime.now())
    status = models.BooleanField(default=False)


    def placeOrder(self):
        self.save()

    @staticmethod
    def get_orders_by_customer(customer_id):
        return Order.objects.filter(customer=customer_id).order_by('-date')
    

store/models/product.py
from django.db import models
from .category import Category
from django.urls import reverse


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    description = models.CharField(max_length=200, default="", null=True, blank=True)
    image = models.ImageField(upload_to = 'uploads/products/')

    @staticmethod
    def get_product_by_id(ids):
        return Product.objects.filter(id__in = ids)

    def get_absolute_url(self):
        return reverse('store:product_details', args=(self.id, ))

    @staticmethod
    def get_products_by_id(ids):
        return Product.objects.filter(id__in =ids)

    @staticmethod
    def get_all_products():
        return Product.objects.all()

    @staticmethod
    def get_all_products_by_categoryid(category_id):
        if category_id:
            return Product.objects.filter(category = category_id)
        else:
            return Product.get_all_products();

store/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

store/views/cart.py
from django.shortcuts import render , redirect , HttpResponseRedirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from store.models.customer import Customer
from django.views import View
from store.models.product import Product

from store.models.cart import Cart
# from store.forms import CartAddProductForm
# Create your views here.



# class Cart(View):
    
#     def get(self,request):
#         mycart = request.session.get('cart')
#         if mycart:
#             ids = list(request.session.get('cart').keys())
#             products = Product.get_product_by_id(ids)
#             print(products)
#             return render(request,'cart.html',{'products':products})
#         else:
#             request.session['cart'] = {}
#             ids = list(request.session.get('cart').keys())
#             products = Product.get_product_by_id(ids)
#             print(products)
#             return render(request,'cart.html',{'products':products})





def add_to_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    cart = Cart.objects.get(user=request.user)
    cart.items.add(product)

    return redirect('cart')




@login_required
def remove_from_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    cart = Cart.objects.get(user=request.user)
    cart.items.remove(product)

    return redirect('cart')


def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'],'update':True})
	context = {
		'cart': cart,
	}
	return render(request,'cart.html', context)

store/views/checkout.py
from django.shortcuts import render, redirect

from django.contrib.auth.hashers import check_password
from store.models.customer import Customer
from django.views import View

from store.models.product import Product
from store.models.orders import Order


class Checkout(View):
    def post(self, request):
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        customer = request.session.get('customer')
        cart = request.session.get('cart')
        products = Product.get_products_by_id(list(cart.keys()))
        print(address, phone, customer, cart, products)

        for product in products:
            print(cart.get(str(product.id)))
            order = Order(customer=Customer(id=customer),
                          product=product,
                          price=product.price,
                          address=address,
                          phone=phone,
                          quantity=cart.get(str(product.id)))
            order.save()
        request.session['cart'] = {}

        return redirect('cart')

store/views/home.py
from django.shortcuts import render , redirect , HttpResponseRedirect

from store.forms import CartAddProductForm
from store.models.product import Product
from store.models.category import Category
from django.views import View
from django.shortcuts import get_object_or_404









# Create your views here.

class Index(View):
    def post(self, request):
        product = request.POST.get('product')
        remove = request.POST.get('remove')
        cart = request.session.get('cart')
        if cart:
            quantity = cart.get(product)
            if quantity:
                if remove:
                    if quantity <= 1:
                        cart.pop(product)
                    else:
                        cart[product] = quantity-1
                else:
                    cart[product] = quantity+1

            else:
                cart[product] = 1

        else:
            cart = {}
            cart[product] = 1
        
        request.session['cart'] = cart
        print(request.session.get('cart'))

        return redirect('home')

    
    def get(self, request):
        allcategory = Category.objects.all()
        allProducts = Product.objects.all()

        list1 = []
        list2 = []



        for categorys in allcategory:
            list1.append(categorys.name)

            # print(list1)

        print("#########################")
        for products in allProducts:
            list2.append(products.category.name)


        mencloth = 0
        womencloth = 0
        vegetables = 0
        mobiles = 0

        for i in range(len(list2)):
            if list1[0] == list2[i]:
                mencloth += 1
            elif list1[1] == list2[i]:
                vegetables += 1
            elif list1[2] == list2[i]:
                mobiles += 1
            
                            

            
        cart = request.session.get('cart')
        if not cart:
            request.session['cart'] = {}
        products = None
        
        categories = Category.get_all_categories()
        categoryId = request.GET.get('category')
        i = 0
        if categoryId:
            products = Product.get_all_products_by_categoryid(categoryId)
            
            
        else:
            products = Product.get_all_products()
        
        
        

        data = {}
        data['products'] = products
        data["categories"] = categories
        data["mencloth"] = mencloth
        data["womencloth"] = womencloth
        data["vegetables"] = vegetables
        data["mobiles"] = mobiles
     
        
        
        print("You Are: ", request.session.get('email'))
        return render(request, "index.html", data)



    
def product_details(request, pk):
    product = get_object_or_404(Product,pk=pk)
    cart_product_form = CartAddProductForm()
    context = {
		'product': product,
		'cart_product_form': cart_product_form,
	}
    return render(request,'product-details.html',context)


store/views/login.py
from django.shortcuts import render , redirect , HttpResponseRedirect

from django.contrib.auth.hashers import  check_password
from store.models.customer import Customer
from django.views import  View


class Login(View):
    return_url = None
    
    def get(self, request):
        Login.return_url = request.GET.get('return_url')
        return render(request, "login.html")
    def post(self, request):
        email = request.POST.get('email')
        password = request.POST.get('password')

        customer = Customer.get_customer_by_email(email)
        
        error_message = None
        if customer:

            flag = check_password(password , customer.password)
            if flag:
                request.session["customer"]  = customer.id
                request.session['first_name'] = customer.first_name
                request.session['last_name'] = customer.last_name
                request.session['email'] = customer.email
                request.session['phone'] = customer.phone

                if Login.return_url:
                    return HttpResponseRedirect(Login.return_url)
                else:
                    Login.return_url = None
                    return redirect('store:home')
            else:
                error_message = "Email Or Password Invalid"

        else:
            error_message = "Email Or Password Invalid"


        return render(request, "login.html", {"error" : error_message})

def logout(request):
    request.session.clear()
    return redirect('store:login')

store/views/orders.py
from django.shortcuts import render, redirect

from django.contrib.auth.hashers import check_password
from store.models.customer import Customer
from django.views import View

from store.models.product import Product
from store.models.orders import Order
from store.middlewares.auth import auth_middleware


class OrderView(View):
    
    def get(self , request ):
        customer = request.session.get('customer')
        orders = Order.get_orders_by_customer(customer)
        print(orders)
        return render(request , 'order.html'  , {'orders' : orders})

store/views/signup.py
from django.shortcuts import render, redirect
from django.contrib.auth. hashers import make_password
from store.models.customer import Customer
from django.views import View


class Signup(View):
    def get(self, request):
        return render(request, 'signup.html')

    def post(self, request):
        postData = request.POST
        first_name = postData.get('firstname')
        last_name = postData.get('lastname')
        phone = postData.get('phone')
        email = postData.get('email')
        password = postData.get('password')
        
        value = {
            'first_name': first_name,
            'last_name': last_name,
            'phone': phone,
            'email': email
        }
        error_message = None

        customer = Customer(first_name=first_name,
                            last_name=last_name,
                            phone=phone,
                            email=email,
                            password=password)
        error_message = self.validateCustomer(customer)

        if not error_message:
            print(first_name, last_name, phone, email, password)
            customer.password = make_password(customer.password)
            customer.register()
            return redirect('/')
        else:
            data = {
                'error': error_message,
                'values': value
            }
            return render(request, 'login.html', data)
    # validation
    def validateCustomer(self, customer):
        error_message = None;
        if (not customer.first_name):
            error_message = "First Name Required !!"
        elif len(customer.first_name) < 4:
            error_message = 'First Name must be 4 char long or more'
        elif not customer.last_name:
            error_message = 'Last Name Required'
        elif len(customer.last_name) < 4:
            error_message = 'Last Name must be 4 char long or more'
        elif not customer.phone:
            error_message = 'Phone Number required'
        elif len(customer.phone) < 11:
            error_message = 'Phone Number must be 10 char Long'
        elif len(customer.password) < 6:
            error_message = 'Password must be 6 char long'
        elif len(customer.email) < 5:
            error_message = 'Email must be 5 char long'
        elif customer.isExists():
            error_message = 'Email Address Already Registered..'

        #saving

        return error_message


store/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Ecommerce</title>
    <style>
      .dropdown-menu
      {
        margin-left: -160px;
      }
      .navbar
      {background-color: #1B1B1E;}
      
    </style>
</head>
<body>
<!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="/">Ecommerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/" style="color: white;">Store<span class="sr-only">(current)</span></a>
            </li>
            
          </ul>
          <ul class="navbar-nav my-2 my-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/cart" style="color: white;">Cart  
                <span class="badge badge-info">{{request.session.cart.keys|length}}</span>
                <span class="sr-only">(current)</span></a>
            </li>
        {% if request.session.customer %}
          <li class="nav-item">
            <a class="nav-link" href="/logout" style="color: white;">Logout<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/orders" style="color: white;">Orders<span class="sr-only">(current)</span></a>
          </li>
          <li>
            <a class="nav-link dropdown-toggle" href="{% url 'store:login' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white;">
                Profile
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#"><i class="fa fa-user mr-2" aria-hidden="true"></i> {{request.session.first_name}} {{request.session.last_name}}  </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#"><i class="fa fa-id-badge mr-2" aria-hidden="true"></i> {{request.session.customer}}</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#"><i class="fa fa-mobile mr-2" aria-hidden="true"></i> {{request.session.phone}}</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#"><i class="fa fa-envelope mr-2" aria-hidden="true"></i> {{request.session.email}}</a>
              </div>
            </li>
        {% else %}
          
          <li class="nav-item">
            <a class="nav-link" href="/signup" style="color: white;">Signup<span class="sr-only" >(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/login" style="color: white;">Login<span class="sr-only">(current)</span></a>
          </li>

         
        
        {% endif %}
            
          </ul>


        </div>
      </nav>

      <!-- End Navbar -->


      {% block content %}


      {% endblock %}


    <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

store/templates/cart.html
{% extends 'base.html' %}


{% block content %}
{% load cart %}

{% load custom_filter %}

<div class="container">
  <div class="border rounded p-4 m-4">
    <h2 class="display-4 text-center">Your Cart</h2>
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Product</th>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Remove</th>
          </tr>
        </thead>
        <tbody>
          {% for product in products %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td><img style="height: 80px;" class="rounded-circle" src="{{product.image.url}}" alt=""></td>
            <td>{{product.name}}</td>
            <td>{{product.price|currency}}</td>
            <td>{{product|cart_quantity:request.session.cart}}</td>
            <td>{{product|price_total:request.session.cart|currency}}</td>

          </tr>
          {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <th class="text-center" colspan="4">Total</th>
            <th>{{products|total_cart_price:request.session.cart}}</th>
            <th></th>
            <td class="remove-item"><a href=""><i class="fa fa-trash-o"></i></a></td>
           
          </tr>
        </tfoot>
      </table>
      <hr>
      {% if request.session.customer %}
    <div class="p-3 m-3">
      <a href="#"  class="btn btn-info float-right btn btn-primary" data-toggle="modal" data-target="#exampleModal">Check Out</a>
    </div>
    {% else %}
    <div class="p-3 m-3">
      <a href="/login"  class="btn btn-info float-right btn btn-primary">Login</a>
    </div>
  {% endif %}
  </div>
</div>


<!-- Button trigger modal -->

{% if request.session.customer %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Check Out Form</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="m2 p-3">
            <form action="{% url 'checkout' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                <label for="">Address</label>
                <input type="text" name="address" id="" class="form-control" required placeholder="Enter Address" aria-describedby="helpId">
              </div>
              <div class="form-group">
                <label for="">Phone</label>
                <input type="text" name="phone" id="" class="form-control" required placeholder="Enter Phone Number" aria-describedby="helpId">
              </div>
              <input type="submit" class="mt-3 btn btn-outline-info col-lg-6" value="Check Out">
            </form>
        </div>
      </div>
      
    </div>
  </div>
</div>
{% endif %}


{% endblock %}

store/templates/index.html
{% extends 'base.html' %}


{% block content %}



{% load cart %}
{% load custom_filter %}

<style>
    .newmain:hover
    {
        background-color: rgb(241, 82, 82);
        color: black;
    }
    
    .jio1
    {
        background-color: thistle;
    }

    .card
    {
        border: 1px solid tomato;
    }
    

    .card img
    {
        width: 100%;
        height: 250px;
        object-fit: cover;
    }
    .btnjio
    {
        width: 50%;
    }

    @media screen and (max-width: 480px) {

        .call1{
            display: none;
        }
      
    }
    
    .carousel-item img
    {
        height: 300px;
        width: 200px;
        object-fit: cover;
    }
  
    
   
</style>



<div class="container mt-3">
<div class="row">

    <!-- Filter -->
    <div class="col-lg-4 mx-auto">
        <div class="list-group">
            <a href="/" class="list-group-item list-group-item-action jio1">All Products</a>

         

            {% for category in categories %}
            
            <a href="/?category={{category.id}}" class="list-group-item list-group-item-action newmain">{{category.name}}</a> 
            
            {% endfor %}
        </div>
    </div>
            <div class="col-lg-2  call1" style="position: absolute; left: 41%;">
            <p class="p-0 nice1" style="margin-top: 33%; "> {{mencloth}} </p> 
            <!-- <p class="arround p-0 nice2" style="margin-top: 30%; ">{{womencloth}}</p> -->
            <p class="arround p-0 nice3" style="margin-top: 13%; ">{{vegetables}}</p>
            <p class="arround p-0 nice3" style="margin-top: 13%; ">{{mobiles}}</p>
        </div>
       
        <div class="col-lg-6">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="https://source.unsplash.com/1600x900/?food" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="https://source.unsplash.com/1600x900/?mobile" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="https://source.unsplash.com/1600x900/?" class="d-block w-100" alt="...">
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
        </div>
            
        
    
    <!-- All Products -->
    <div id="products"  class="col-lg-12 mx-auto mt-5">
        <div class="row mx-auto">
            {% for prods in products %}
            
            <div class="card mx-auto mb-3" style="width: 22rem;" id="{{prods.id}}">
                <img src="{{prods.image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title text-dark"><a href="{% url 'store:product_details'  prods.id %}">{{prods.name | capfirst}}</a></h5>
                  <p class="card-text">{{prods.price|currency}}</p>        
                </div>

                <div class="card-footer">
            
                   <a href="#" class="btn btn-primary btn-md my-0 p">
                        Add to cart
                        <i class="fa fa-shopping-cart ml-1"></i>
                    </a> 
                   
                </div>

               
              </div>
            
            {% endfor %}
            </div>
    </div>
</div>
</div>
{% endblock %}
    <!-- jQuery library -->

store/templates/login.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <div class="p-4 m-4  col-lg-5 mx-auto mt-4 mb-4" >
        
      
        <form action="" class="border rounded pt-3" method="POST">
            {% csrf_token %}
            <h3 class="text-center mt-5 alert alert-dark border rounded ">Login Here</h2>
                {% if error %}
<div class="alert alert-danger alert-dismissible" role="alert">
    {{error}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
 </div>
 {% endif %}
            <!-- Email -->
            <div class="form-group">
                <label for="example3">Email</label>
                <input type="email" value="{{values.email}}" name="email" class="form-control form-control-sm" id="example3" aria-describedby="emailHelp" required />
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              </div>
              <div class="form-group">
                <label for="example4">Password</label>
                <input type="password" name="password" class="form-control form-control-sm" id="example4" required />
              </div>
              <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
              </div>
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-info col-lg-4">Login</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

store/templates/product-details.html
{% extends 'base.html' %}

{% block content %}

<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <img src="{{ product.image.url }}" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-4">

          <div class="mb-3">
            <h2 style='color: #2009da;font-weight: bold;'>{{product.name | capfirst}}</h2>
          </div>

          <div class="product-price" style="font-size: 21px;">${{product.price | floatformat:2 }}</div>
        <br><br>
          <p class="lead font-weight-bold">Description</p>

          <p>{{ product.description }}</p>

          <a href="{% url 'store:add_to_cart' product_id=product.id %}" class="btn btn-primary btn-md my-0 p">
            Add to cart
            <i class="fa fa-shopping-cart ml-1"></i>
          </a>
          <a href="{{ product.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
            Remove from cart
          </a>

        </div>
        <!--Content-->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <hr>

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 text-center">

        <h4 class="my-4 h4">Additional information</h4>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
          voluptates,
          quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->


  </div>
</main>



{% endblock %}